/**
 * EMPLOYEES
 */
export const FETCH_LIST_EMPLOYEE = 'FETCH_LIST_EMPLOYEE';
export const FETCH_LIST_EMPLOYEE_SUCCESS = 'FETCH_LIST_EMPLOYEE_SUCCESS';
export const FETCH_LIST_EMPLOYEE_ERROR = 'FETCH_LIST_EMPLOYEE_ERROR';
